//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач
{
    using System;
    using System.Collections.Generic;
    
    public partial class LodgersGuests
    {
        public string FIO { get; set; }
        public int LodgerID { get; set; }
        public bool Pol { get; set; }
        public string Passport { get; set; }
        public int ID { get; set; }
        public int Phone { get; set; }
    
        public virtual Lodgers Lodgers { get; set; }
    }
}
