//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lodgers_Kids
    {
        public string FIO { get; set; }
        public int Parent_Passport { get; set; }
        public bool Pol { get; set; }
        public string Svidet_Num { get; set; }
    
        public virtual Lodgers Lodgers { get; set; }
    }
}
