//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersReg
    {
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int LodgerPass { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime StopDate { get; set; }
        public string WorkerFIO { get; set; }
    
        public virtual Lodgers Lodgers { get; set; }
    }
}
